# Generated by Django 2.0 on 2018-02-09 06:11

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('buysell', '0013_auto_20171227_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=255)),
                ('customerName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Enter keywords for your wants. Use a comma to separate the wants.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Wants'),
        ),
    ]
